// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Filter: typeof import('./src/components/Filter.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NTag: typeof import('naive-ui')['NTag']
    NThing: typeof import('naive-ui')['NThing']
    ProjectIcon: typeof import('./src/components/icons/ProjectIcon.vue')['default']
    ProjectList: typeof import('./src/components/ProjectList.vue')['default']
    RightPanel: typeof import('./src/components/RightPanel.vue')['default']
    SearchIcon: typeof import('./src/components/icons/SearchIcon.vue')['default']
    SelectedGreenIcon: typeof import('./src/components/icons/SelectedGreenIcon.vue')['default']
    SelectedIcon: typeof import('./src/components/icons/SelectedIcon.vue')['default']
    WebApi: typeof import('./src/components/options/WebApi.vue')['default']
  }
}
